spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: dome-service-config-dev

---
spring:
     profiles: test
     application:
       name: dome-service-config-test