server:
  port: 6001
spring:
  profiles: cloud-admin-server
  application:
    name: admin-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6002/eureka/


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
