spring:
  profiles: eurekadev
  application:
    name: eurekaserver


server:
  port: 6002


eureka:
  instance:
    hostname: localhost

  client:
    service-url:
      defaultZone: http://localhost:6002/eureka/
    register-with-eureka: false
    fetch-registry: false